In [1]:
import numpy as np

In [15]:
a=np.arange(1,21,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
b=np.arange(1,21,1)
print(b)
i=0
while i <= 9:
    print(b[2*i+1])
    i=i+1

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
4
6
8
10
12
14
16
18
20


In [40]:
c=np.arange(1,21,1)
print(c)
i=0
while i <= 18:
    i += 1
    if b[i] % 3 != 0:
        continue    
    print(i+1)    

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
3
6
9
12
15
18
